# py.test gives the testing functionality
import pytest

# We'll use our bioinformatics dictionary from before
import bioinfo_dicts as bd

import lesson_36

DNA = 'ATGGAGAACAACGAAGCCCCCTCCCCCTCGGGATCCAACAACAACGAGAACAACAATGCAGCCCAGAAGAAGCTGCAGCAGACCCAAGCCAAGGTGGACGAGGTGGTCGGGATTATGCGTGTGAACGTGGAGAAGGTCCTGGAGCGGGACCAGAAGCTATCGGAACTGGGCGAGCGTGCGGATCAGCTGGAGCAGGGAGCATCCCAGTTCGAGCAGCAGGCCGGCAAGCTGAAGCGCAAGCAATGGTGGGCCAACATGAAGATGATGATCATTCTGGGCGTGATAGCCGTTGTGCTGCTCATCATCGTTCTGGTGTCGCTTTTCAATTGA'

protein = 'MENNEAPSPSGSNNNENNNAAQKKLQQTQAKVDEVVGIMRVNVEKVLERDQKLSELGERADQLEQGASQFEQQAGKLKRKQWWANMKMMIILGVIAVVLLIIVLVSLFN'

def test_find_codon():
    assert lesson_36.find_codon_lesson6('ATG', DNA) == 0
    assert lesson_36.find_codon_lesson6('AAT', DNA) == 54
    assert lesson_36.find_codon_lesson6('TGT', DNA) == 119
    assert lesson_36.find_codon_lesson6('TGC', DNA) == 56
